# Generated by Django 4.1.6 on 2023-05-19 05:15

import cmscore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmi_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_name', models.CharField(max_length=255)),
                ('About_image', models.ImageField(null=True, upload_to='Consortium')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('consortium_desc', models.TextField(blank=True, null=True)),
                ('consortium_objectives', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('proj_id', models.IntegerField(blank=True, null=True)),
                ('prog_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='cmi_models.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='cmi_models.project')),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('carousel', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cmscore.album')),
            ],
            options={
                'db_table': 'album_photo',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('expert', 'expert'), ('farm', 'farm'), ('support', 'support')], max_length=255)),
                ('content_detail', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loginbg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_BG', models.ImageField(upload_to='loginbg')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostpcaarrd_ExDi_name', models.CharField(blank=True, max_length=255)),
                ('dostpcaarrd_ExDi_img', models.ImageField(blank=True, upload_to='organization')),
                ('wmsupres_rrdcchair_exdi_name', models.CharField(blank=True, max_length=255)),
                ('wmsupres_rrdcchair_exdi_img', models.ImageField(blank=True, upload_to='organization')),
                ('depu_di_name', models.CharField(blank=True, max_length=255)),
                ('depu_di_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_ZSCMST_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_ZSCMST_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_DA_RFO_IX_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_DA_RFO_IX_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXMB_DA_BAR_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_DA_BAR_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_JHCSC_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_JHCSC_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_PHILFIDA_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_PHILFIDA_img', models.ImageField(blank=True, upload_to='organization')),
                ('WESMAARRDEC_Dir_name', models.CharField(blank=True, max_length=255)),
                ('WESMAARRDEC_Dir_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_R_and_D_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_R_and_D_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_Tech_Trans_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_Tech_Trans_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_ICT_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_ICT_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_Sci_Com_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_Sci_Com_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup1_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup1_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup2_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup2_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup3_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup3_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup4_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup4_img', models.ImageField(blank=True, upload_to='organization')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='Slide/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cmscore_slide',
            },
        ),
        migrations.CreateModel(
            name='AlbumPhotoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to=cmscore.models.get_existing_file_name, verbose_name='Image')),
                ('albumphoto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmscore.albumphoto')),
            ],
        ),
    ]
