# Generated by Django 4.1.6 on 2023-04-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consortium_code', models.CharField(max_length=50)),
                ('consortium_name', models.CharField(max_length=255)),
                ('consortium_address', models.CharField(max_length=255)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('consortium_logo', models.ImageField(null=True, upload_to='Consortium')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('consortium_desc', models.TextField(blank=True, null=True)),
                ('consortium_objectives', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('proj_id', models.IntegerField(blank=True, null=True)),
                ('prog_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('content_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostpcaarrd_ExDi_name', models.CharField(blank=True, max_length=255)),
                ('dostpcaarrd_ExDi_img', models.ImageField(blank=True, upload_to='organization')),
                ('wmsupres_rrdcchair_exdi_name', models.CharField(blank=True, max_length=255)),
                ('wmsupres_rrdcchair_exdi_img', models.ImageField(blank=True, upload_to='organization')),
                ('depu_di_name', models.CharField(blank=True, max_length=255)),
                ('depu_di_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_ZSCMST_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_ZSCMST_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_DA_RFO_IX_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_DA_RFO_IX_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXMB_DA_BAR_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_DA_BAR_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_JHCSC_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_JHCSC_img', models.ImageField(blank=True, upload_to='organization')),
                ('EXBM_PHILFIDA_name', models.CharField(blank=True, max_length=255)),
                ('EXBM_PHILFIDA_img', models.ImageField(blank=True, upload_to='organization')),
                ('WESMAARRDEC_Dir_name', models.CharField(blank=True, max_length=255)),
                ('WESMAARRDEC_Dir_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_R_and_D_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_R_and_D_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_Tech_Trans_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_Tech_Trans_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_ICT_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_ICT_img', models.ImageField(blank=True, upload_to='organization')),
                ('Clus_Coord_Sci_Com_name', models.CharField(blank=True, max_length=255)),
                ('Clus_Coord_Sci_Com_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup1_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup1_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup2_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup2_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup3_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup3_img', models.ImageField(blank=True, upload_to='organization')),
                ('Management_sup4_name', models.CharField(blank=True, max_length=255)),
                ('Management_sup4_img', models.ImageField(blank=True, upload_to='organization')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='Slide/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='AlbumPhoto')),
                ('slide', models.BooleanField(default=False)),
                ('carousel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cmscore.album')),
            ],
        ),
    ]
