# Generated by Django 4.1.6 on 2023-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0002_alter_album_created_at_alter_album_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='img',
            field=models.ImageField(null=True, upload_to='AlbumPhoto'),
        ),
    ]
