# Generated by Django 4.1.6 on 2023-03-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0002_alter_organization_clus_coord_ict_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consortium',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
