# Generated by Django 4.1.6 on 2023-05-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmi_models', '0001_initial'),
        ('cmscore', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='cmi_models.program'),
        ),
        migrations.AlterField(
            model_name='album',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='cmi_models.project'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
