# Generated by Django 4.1.6 on 2023-03-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0003_alter_consortium_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cmscore.album'),
        ),
    ]
