# Generated by Django 4.1.6 on 2023-03-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0003_alter_albumphoto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to='cmscore.album'),
        ),
        migrations.AlterField(
            model_name='consortium',
            name='consortium_logo',
            field=models.ImageField(null=True, upload_to='Consortium'),
        ),
    ]
