# Generated by Django 4.1.6 on 2023-05-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0003_content_created_by_alter_album_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginbg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_BG', models.ImageField(upload_to='loginbg')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
