# Generated by Django 4.1.6 on 2023-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0004_loginbg_alter_about_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhotoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='albumphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='image',
            field=models.ManyToManyField(to='cmscore.albumphoto'),
        ),
    ]
