# Generated by Django 4.1.6 on 2023-03-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0004_alter_albumphoto_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumphoto',
            old_name='img',
            new_name='image',
        ),
    ]
