# Generated by Django 4.1.6 on 2023-05-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0005_albumphotoimages_remove_albumphoto_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumphoto',
            old_name='image',
            new_name='images',
        ),
    ]
