# Generated by Django 4.1.6 on 2023-05-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0006_rename_image_albumphoto_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphotoimages',
            name='album_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo_images', to='cmscore.albumphoto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='images',
            field=models.ManyToManyField(to='cmscore.albumphotoimages'),
        ),
    ]
