# Generated by Django 4.1.6 on 2023-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0007_albumphotoimages_album_photo_alter_albumphoto_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='images',
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(null=True, upload_to='AlbumPhoto'),
        ),
        migrations.DeleteModel(
            name='AlbumPhotoImages',
        ),
    ]
