# Generated by Django 4.1.6 on 2023-05-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0008_remove_albumphoto_images_albumphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlbumPhotoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Images/')),
                ('albumphoto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmscore.albumphoto')),
            ],
        ),
    ]
