# Generated by Django 4.1.6 on 2023-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0009_alter_albumphoto_image_albumphotoimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='albumphotoimages',
            name='images',
            field=models.FileField(upload_to='Images/'),
        ),
    ]
