# Generated by Django 4.1.6 on 2023-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0010_alter_albumphoto_image_alter_albumphotoimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphotoimages',
            name='images',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
