# Generated by Django 4.1.6 on 2023-05-14 17:59

import cmscore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0011_alter_albumphotoimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to=cmscore.models.get_existing_file_name, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='albumphotoimages',
            name='images',
            field=models.ImageField(blank=True, upload_to=cmscore.models.get_existing_file_name, verbose_name='Image'),
        ),
    ]
