# Generated by Django 4.1.6 on 2023-05-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0013_remove_albumphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='slide',
        ),
    ]
