# Generated by Django 4.1.6 on 2023-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscore', '0014_remove_albumphoto_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
