# Generated by Django 4.1.6 on 2023-03-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblg', '0002_alter_comment_name_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slide',
            new_name='featured',
        ),
    ]
